import React from 'react';
import classes from './ExpandedBlog.css';

const single_blog = (props) => (
  <div className={classes.EntireBlog}>
    <h2>Hurga Durga... A Durga Hurga </h2>
    <p>hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga </p>
    <p>hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga </p>
    <p>hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga </p>
    <p>hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga </p>
    <p>hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga </p>
    <p>hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga </p>
    <p>hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga hurga durga </p>

  </div>

);

export default single_blog;
